configuration: Release

build:
  project: WormsSchemeConverter\WormsScheme.sln
  verbosity: minimal

after_build:
  - cmd: WormsSchemeConverter\WormsScheme\bin\release\WormsScheme.exe "Uber Coolest Options.txt" "Uber Coolest Options %APPVEYOR_BUILD_VERSION%.wsc"
  - cmd: WormsSchemeConverter\WormsScheme\bin\release\WormsScheme.exe "Speed Worms.txt" "Speed Worms %APPVEYOR_BUILD_VERSION%.wsc"
  - cmd: WormsSchemeConverter\WormsScheme\bin\release\WormsScheme.exe "Christmas 2017.txt" "Christmas 2017 %APPVEYOR_BUILD_VERSION%.wsc"
  - cmd: appveyor PushArtifact "Uber Coolest Options %APPVEYOR_BUILD_VERSION%.wsc"
  - cmd: appveyor PushArtifact "Speed Worms %APPVEYOR_BUILD_VERSION%.wsc"
  - cmd: appveyor PushArtifact "Christmas 2017 %APPVEYOR_BUILD_VERSION%.wsc"

deploy:
  - provider: GitHub
    auth_token:
      secure: A7+/5adwhz9NXkJeVJpckt7wIcfIOVr1M8KPMHrOD+TknNaV6CX2XrKR21+QS9ko
    artifact: /.*\.wsc/
    draft: false
    prerelease: false
    description: ''
    on:
      branch: master
      appveyor_repo_tag: false
