name: CLI

on:
  push:
    paths:
    - "CommandLine/**"

jobs:
  build-cli-windows:
    name: Build CLI - Windows
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: cd CommandLine; make windows
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: win-x64
        path: CommandLine/.artifacts/win-x64/

  build-cli-linux:
    name: Build CLI - Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: cd CommandLine; make linux
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: linux-x64
        path: CommandLine/.artifacts/linux-x64/



  release-cli-windows:
    name: Release CLI - Windows
    needs: build-cli-windows
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: win-x64
    - name: Release
      run: cd CommandLine; make release-github ReleaseDir=../win-x64 GitHubAuthToken=${{ secrets.GITHUB_TOKEN }} GitHubRepo=${{ github.repository }}
