name: Schemes

on:
  push:
    paths:
    - "Schemes/**"
    - ".build/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: cd Schemes; make schemes
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: RGSchemes
        path: Schemes/.artifacts/

  release:
    name: Release - GitHub
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: RGSchemes
        path: Schemes/.artifacts/
    - name: Release
      run: cd Schemes; make release-github GitHubAuthToken=${{ secrets.GITHUB_TOKEN }} GitHubRepo=${{ github.repository }}
